export const DEFAULT_LIMITS = {
  USER_SIGNATURES: 10,
  PROJECT_TEMPLATE_COUNT: 50,
  FREE_PROJECT_TEMPLATE_COUNT: 5,
  GLOBAL_TEMPLATE_COUNT: 30,
  FREE_GLOBAL_TEMPLATE_COUNT: 5,
  PERSONAL_TEMPLATE_COUNT: 30,
  FREE_PERSONAL_TEMPLATE_COUNT: 5,
  TEMPLATE_NAME: 64,
};
